---
- name: install packages
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - htop
    - tmux
    - wget
  tags: dev_tools

- include: vim.yml
- include: git.yml
- include: bash.yml
- include: adminer.yml
