---
- name: install and configure db servers
  hosts: db_servers
  remote_user: '{{ user }}'
  become: yes

  roles:
    - db

- name: install and configure web servers and application
  hosts: web_servers
  remote_user: '{{ user }}'
  become: yes

  roles:
    - web
    - dev
